# Generated by Django 5.2.16 on 2026-08-30 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer_primary', 'Footer — primary'), ('footer_secondary', 'Footer — secondary'), ('legal', 'Footer — legal')], max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['location'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(help_text='Public URL, for example: about-us', max_length=140, unique=True)),
                ('navigation_title', models.CharField(blank=True, max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('is_homepage', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=170)),
                ('social_image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='College of Project Control', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=180)),
                ('logo_text', models.CharField(default='College of Project Control', max_length=80)),
                ('logo_url', models.URLField(blank=True)),
                ('primary_cta_label', models.CharField(blank=True, max_length=60)),
                ('primary_cta_url', models.CharField(blank=True, max_length=240)),
                ('announcement_enabled', models.BooleanField(default=False)),
                ('announcement_text', models.CharField(blank=True, max_length=180)),
                ('announcement_url', models.CharField(blank=True, max_length=240)),
                ('footer_description', models.TextField(blank=True)),
                ('footer_cta_title', models.CharField(blank=True, max_length=120)),
                ('footer_cta_body', models.TextField(blank=True)),
                ('footer_cta_label', models.CharField(blank=True, max_length=60)),
                ('footer_cta_url', models.CharField(blank=True, max_length=240)),
                ('copyright_name', models.CharField(default='College of Project Control', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=240)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.menuitem')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.navigationmenu')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_name', models.CharField(help_text='Only shown in the dashboard, for example: Homepage hero', max_length=100)),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('rich_text', 'Rich text'), ('feature_grid', 'Feature grid'), ('card_grid', 'Card grid'), ('stats', 'Statistics'), ('media_copy', 'Media and copy'), ('testimonial', 'Testimonial'), ('faq', 'Frequently asked questions'), ('cta', 'Call to action')], max_length=32)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('anchor_id', models.SlugField(blank=True, max_length=80)),
                ('style_variant', models.CharField(blank=True, default='default', max_length=60)),
                ('content', models.JSONField(default=dict, help_text='Structured section content. Hero example: {"eyebrow":"Welcome","title":"Page title","body":"Intro copy","primaryCta":{"label":"Get started","url":"/contact"}}')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.page')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('page', 'order'), name='unique_section_order_per_page')],
            },
        ),
    ]
