# Generated by Django 5.2.16 on 2026-08-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('rich_text', 'Rich text'), ('feature_grid', 'Feature grid'), ('card_grid', 'Card grid'), ('stats', 'Statistics'), ('media_copy', 'Media and copy'), ('testimonial', 'Testimonial'), ('faq', 'Frequently asked questions'), ('cta', 'Call to action'), ('logo_marquee', 'Logo marquee'), ('funding_calculator', 'Funding calculator')], max_length=32),
        ),
    ]
