# Generated by Django 5.2.16 on 2026-09-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_enquiry_and_lead_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('qualification', models.CharField(blank=True, help_text='e.g. MSc Strategic Project Management', max_length=200)),
                ('focus', models.TextField(help_text='What this coach helps learners with.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='coaches/%Y/%m/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Unpublished coaches are saved as a draft and hidden from the site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded photo. Takes priority over the image URL below when set.', null=True, upload_to='mentors/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='image_url',
            field=models.CharField(blank=True, help_text='Used only when no image is uploaded. Optional absolute URL or a local path such as /images/mentor-name.webp.', max_length=500),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Unpublished mentors are saved as a draft and hidden from the site.'),
        ),
    ]
