# Generated by Django 5.2.16 on 2026-09-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_coach_mentorprofile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional label, used as image alt text and shown in the dashboard.', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/%Y/%m/')),
                ('logo_url', models.CharField(blank=True, help_text='Used only when no logo is uploaded. Paste a direct image link.', max_length=500)),
                ('link_url', models.URLField(blank=True, help_text='Optional. Where the logo links to when clicked.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Unpublished partners are saved as a draft and hidden from the site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
