# Generated by Django 5.2.16 on 2026-09-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, help_text='e.g. Masterclass, Webinar, Information Session.', max_length=80)),
                ('format', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person')], default='online', max_length=16)),
                ('cadence', models.CharField(blank=True, help_text='e.g. Monthly, or a specific date/time.', max_length=160)),
                ('description', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, default='Register Your Interest', max_length=80)),
                ('cta_href', models.CharField(blank=True, default='/contact', max_length=240)),
                ('external_id', models.CharField(blank=True, help_text='ID from an external source (e.g. Eventbrite), used to avoid duplicate imports when syncing.', max_length=120)),
                ('source_url', models.URLField(blank=True, help_text='Link to the event on the external platform, if any.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Unpublished events are saved as a draft and hidden from the site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
