# Generated by Django 5.2.16 on 2026-09-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_professionalcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, help_text='Short focus line shown on the sector card.', max_length=300)),
                ('slug', models.SlugField(help_text="Matches the sector's dedicated landing page, e.g. construction, engineering, public-sector, energy.", max_length=60, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Remix Icon class, e.g. ri-building-line', max_length=60)),
                ('image', models.ImageField(blank=True, help_text="Used as the card background and the sector's own page hero background. Takes priority over the image URL below.", null=True, upload_to='sectors/%Y/%m/')),
                ('image_url', models.CharField(blank=True, help_text='Used only when no image is uploaded. Paste a direct image link.', max_length=500)),
                ('link_url', models.CharField(blank=True, help_text="Where this sector's card links to.", max_length=240)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Unpublished sectors are saved as a draft and hidden from the site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
