# Generated by Django 5.2.16 on 2026-09-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpcImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
