# Generated by Django 5.2.16 on 2026-09-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_seed_ipc_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('excerpt', models.TextField(max_length=600)),
                ('content', models.TextField(help_text='Use blank lines between paragraphs, ## for headings and - for list items.')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(default='College of Project Controls', max_length=160)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/')),
                ('image_url', models.CharField(blank=True, max_length=2000)),
                ('image_alt', models.CharField(blank=True, max_length=240)),
                ('read_minutes', models.PositiveSmallIntegerField(default=5)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-published_at', '-id'],
            },
        ),
    ]
