# Generated by Django 5.2.16 on 2026-09-09 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSyncControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_encrypted', models.TextField(blank=True)),
                ('organization_id', models.CharField(blank=True, max_length=120)),
                ('public_base_url', models.URLField(blank=True, max_length=500)),
                ('connection_checked_at', models.DateTimeField(blank=True, null=True)),
                ('connection_ok', models.BooleanField(default=False)),
                ('auto_sync', models.BooleanField(default=True)),
                ('interval_minutes', models.PositiveSmallIntegerField(default=15)),
                ('show_uncategorized', models.BooleanField(default=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=100)),
                ('last_full_sync', models.DateTimeField(blank=True, null=True)),
                ('next_full_sync', models.DateTimeField(blank=True, null=True)),
                ('worker_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('lock_until', models.DateTimeField(blank=True, null=True)),
                ('lock_owner', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EventSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='full', max_length=16)),
                ('resource_path', models.CharField(blank=True, max_length=240)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('due_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='highlights_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='event',
            name='image_alt',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='organization_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='event',
            name='price_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='remote_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='remote_status',
            field=models.CharField(default='live', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='sales_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=260, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('eventbrite', 'Eventbrite')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='source_is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='summary',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='event',
            name='sync_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='Europe/London', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='cta_href',
            field=models.CharField(blank=True, default='/contact', max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='source_url',
            field=models.URLField(blank=True, help_text='Link to the event on the external platform, if any.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=240),
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('kind', models.CharField(choices=[('eventbrite', 'Eventbrite category'), ('local', 'Local classification'), ('programme', 'Programme')], default='local', max_length=16)),
                ('remote_id', models.CharField(blank=True, max_length=120)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('remote_id', ''), _negated=True), fields=('kind', 'remote_id'), name='unique_event_category_remote')],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='classifications',
            field=models.ManyToManyField(blank=True, related_name='classified_events', to='content.eventcategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='source_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_events', to='content.eventcategory'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'eventbrite'), models.Q(('external_id', ''), _negated=True)), fields=('organization_id', 'external_id'), name='unique_eventbrite_event'),
        ),
        migrations.AddIndex(
            model_name='eventsyncjob',
            index=models.Index(fields=['status', 'due_at'], name='content_eve_status_f6c932_idx'),
        ),
    ]
