# Generated by Django 5.2.16 on 2026-09-10 07:54

import apps.content.review_storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_event_slugs_and_classifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('programme', models.CharField(choices=[('associate-project-manager-level-4', 'Associate Project Manager Level 4'), ('pcp-level-6', 'Project Controls Professional Level 6'), ('strategic-pcp', 'PCP — Strategic Route'), ('operational-pcp', 'PCP — Operational Route'), ('strategic-operational-pcp', 'PCP — Strategic & Operational Route'), ('pmo-pcp', 'PCP — PMO & Governance Route'), ('chartered-pmo-pathway', 'Chartered PMO Pathway'), ('construction', 'PCP — Construction Route'), ('engineering', 'PCP — Engineering, Manufacturing & Aerospace Route'), ('public-sector', 'PCP — Public Sector & Councils Route'), ('energy', 'PCP — Energy, Oil, Gas & Utilities Route'), ('commercial', 'Commercial Project Controls Route'), ('ipc', 'Institute of Project Controls')], max_length=80)),
                ('reviewer_type', models.CharField(choices=[('professional', 'Professional'), ('employer', 'Employer')], default='professional', max_length=20)),
                ('photo', models.ImageField(storage=apps.content.review_storage.private_review_storage, upload_to=apps.content.review_storage.review_photo_path)),
                ('review', models.TextField(max_length=4000)),
                ('consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('moderation_notes', models.TextField(blank=True, max_length=2000)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', 'order', '-created_at', '-id'],
            },
        ),
    ]
