# Generated by Django 5.2.16 on 2026-09-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalcredential',
            name='name',
            field=models.CharField(blank=True, help_text='Optional. Certificate, awarding body or professional pathway name, for example: APM.', max_length=120),
        ),
    ]
