# Generated by Django 5.2.16 on 2026-09-10 12:40

import apps.content.review_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_professional_credential_name_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image_url',
            field=models.CharField(blank=True, help_text='Used only when no photo is uploaded. Paste a direct image link.', max_length=500),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, storage=apps.content.review_storage.private_review_storage, upload_to=apps.content.review_storage.review_photo_path),
        ),
    ]
