# Generated by Django 5.2.16 on 2026-09-14 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_followed_up_requests(apps, schema_editor):
    Enquiry = apps.get_model('content', 'Enquiry')
    from django.db.models import F
    Enquiry.objects.exclude(status='new').update(read_at=F('updated_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_testimonial_photo_optional_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='follow_up_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='read_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(mark_existing_followed_up_requests, migrations.RunPython.noop),
    ]
