# Generated by Django 5.2.16 on 2026-09-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_casestudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_heading',
            field=models.CharField(default='Website under construction', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(default="We're making updates to the website. Enter the access code to preview the work in progress."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_pin_hash',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
