# Generated by Django 5.2.17 on 2026-09-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_sitesettings_maintenance_enabled_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_published', 'published_at'], name='article_published_idx'),
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['is_published', 'published_at'], name='casestudy_published_idx'),
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['sector'], name='casestudy_sector_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active', 'starts_at'], name='event_active_start_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_featured', 'order'], name='event_featured_order_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['remote_status'], name='event_remote_status_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['status'], name='page_status_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['is_homepage'], name='page_homepage_idx'),
        ),
        migrations.AddIndex(
            model_name='shortcourse',
            index=models.Index(fields=['is_active', 'order', 'title'], name='shortcourse_active_order_idx'),
        ),
    ]
