# Generated by Django 5.2.17 on 2026-09-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_article_article_published_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='page',
            name='page_homepage_idx',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active', 'ends_at'], name='event_active_end_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['is_homepage', 'status'], name='page_home_idx'),
        ),
    ]
