# Generated by Django 5.2.17 on 2026-09-27 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_remove_page_page_homepage_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['is_published', 'is_featured'], name='casestudy_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['status', '-is_featured'], name='testimonial_status_idx'),
        ),
    ]
