# Generated by Django 5.2.16 on 2026-09-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='internal_name',
            field=models.CharField(blank=True, help_text='Human-readable label shown in the dashboard, e.g. "Hero", "Why Join"', max_length=140),
        ),
    ]
