# Generated by Django 5.2.16 on 2026-09-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_pagecontentrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontentrevision',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
