# Generated by Django 5.2.16 on 2026-09-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_pagecontentrevision_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/'),
        ),
    ]
