# Generated by Django 5.2.16 on 2026-09-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatQuota',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('used', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('website', 'Website'), ('faq', 'Q&A'), ('document', 'Document')], max_length=16)),
                ('reference_path', models.CharField(blank=True, max_length=240)),
                ('content', models.TextField(max_length=80000)),
                ('is_active', models.BooleanField(default=False)),
                ('import_key', models.CharField(blank=True, editable=False, max_length=240, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
