# Generated by Django 5.2.17 on 2026-09-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_assistantsettings'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='knowledgesource',
            index=models.Index(fields=['is_active', '-updated_at'], name='source_active_updated_idx'),
        ),
    ]
