from pathlib import Path
import json
p=Path('frontend/src/pages/operational-pcp-public-sector/page.tsx');old=p.read_text(encoding='utf-8');hero=old[old.index('<header className='):old.index('</header>')+9]
def q(s):return '{'+json.dumps(s,ensure_ascii=False)+'}'
def grid(items,cols=3):return '<div className="grid gap-6 md:grid-cols-2 '+('lg:grid-cols-3' if cols==3 else '')+'">'+''.join('<article className="space-y-3 rounded-2xl border border-background-200 bg-white p-6"><h3 className="text-xl">'+q(t)+'</h3><p className="leading-relaxed text-foreground-600">'+q(d)+'</p></article>' for t,d in items)+'</div>'
def link(h,t):return '<SiteLink href="'+h+'" className="btn-primary inline-flex min-h-12 items-center px-6 font-bold">'+t+'</SiteLink>'
def sec(id,tag,title,intro,body):return '<section id="'+id+'" className="scroll-mt-44 py-16 odd:bg-background-100 md:py-20"><div className="container-site space-y-8"><div className="max-w-3xl space-y-4"><p className="text-xs font-bold uppercase tracking-[.15em] text-accent-700">'+q(tag)+'</p><h2 className="text-3xl md:text-4xl">'+q(title)+'</h2><p className="leading-relaxed text-foreground-600">'+q(intro)+'</p></div>'+body+'</div></section>'
parts=[]
parts.append(sec('challenge','Why public-sector delivery is different','Project capability must remain clear, auditable and defensible.','Public programmes operate across formal governance, multi-supplier delivery, constrained budgets, complex stakeholders and scrutiny. Decisions must connect scope, affordability, risk, service outcomes and public value.',grid([
('Formal baselines and controlled change','Material changes to scope, cost or timetable require impact analysis, approval routes and traceable decisions.'),('Accountability and value for money','Reporting supports governance, assurance and responsible use of public funds, with clear recommendations for intervention.'),('Multi-supplier delivery','Coordinate dependencies, commercial interfaces and shared milestones across departments, partners and suppliers.'),('Data, security and service continuity','Respect information governance, access requirements, resilience and critical-service responsibilities.')],2)))
parts.append(sec('pathways','Role-to-programme pathway','Match the apprenticeship to the employee’s real responsibilities.','The right route depends on prior learning, responsibility and the substantial new capability the employee needs to develop. Existing employees may learn while remaining in a suitable role.',grid([
('Associate Project Manager Level 4','For Project Support Officers, Project Coordinators, Junior PMO Analysts and employees coordinating workstreams, stakeholders, risks and governance.'),('Project Controls Professional Level 6','For planners, cost professionals, risk specialists, controls engineers and PMO teams integrating schedule, cost, risk, change and delivery performance.')],2)+'<div className="flex flex-wrap gap-3">'+link('/associate-project-manager-level-4','Explore Level 4')+link('/project-controls-professional-level-6','Explore Level 6')+'</div>'))
parts.append(sec('capability','The project-controls capability model','Five capabilities for accountable public-project delivery.','Build reliable controls that give senior leaders decision-ready insight, support earlier intervention and connect delivery to approved programme baselines.',grid([
('Planning and scheduling','Roadmaps, baselines, milestones, dependencies, progress and scenario planning.'),('Cost and forecasting','Budgets, commitments, estimates, variance, affordability and forecast confidence.'),('Risk and change','Risk appetite, escalation, impact assessment, change control and mitigation.'),('Performance reporting','Integrated data, RAG status, trends, dashboards and a decision-ready narrative.'),('Governance and assurance','Evidence, auditability, approvals, public accountability and value for money.')])) )
parts.append(sec('governance','Learning grounded in government delivery','Apply project capability within public-sector governance.','Contextualise workplace learning to the frameworks, responsibilities and assurance arrangements that apply to the organisation.',grid([
('Project Delivery Functional Standard','Governance, assurance, roles and consistent delivery practice.'),('Green Book and Five Case Model','Appraisal, business cases, options, benefits and demonstrable public value.'),('Orange Book','Risk management embedded in governance, decisions and organisational objectives.'),('Managing Public Money','Probity, regularity, affordability, financial discipline and responsible decision-making.')],2)))
parts.append(sec('careers','Career progression','Build a visible project-delivery capability pipeline.','Develop capability from project support through specialist controls and senior programme leadership. These are illustrative progression opportunities, not guaranteed promotions.',grid([
('01 · Project support','Project Support Officer, Project Coordinator or Junior PMO Analyst.'),('02 · Project delivery','Project Manager, Workstream Lead or developing delivery professional.'),('03 · Specialist controls','Planner, Scheduler, Cost Engineer, Risk Professional or Controls Engineer.'),('04 · Controls leadership','Project Controls Lead, Programme Controller or PMO Controls Manager.'),('05 · Programme leadership','Programme Controls Manager, Head of PMO or senior project-delivery leader.')])) )
parts.append(sec('delivery','Employer journey','Learn, apply, assure and evidence.','The employer, learner and College agree the development need, learning plan, responsibilities and evidence approach before enrolment.',grid([
('01 · Capability review','Discuss roles, organisational priorities and target capability.'),('02 · Eligibility and prior learning','Review the employee, workplace, existing knowledge and funding route.'),('03 · Enrolment and learning plan','Agree responsibilities, support, development goals and evidence opportunities.'),('04 · Applied development','Live online sessions, coaching, workplace application and progress reviews.'),('05 · Gateway and EPA','Review occupational competence, required evidence and readiness for independent assessment.')])) )
parts.append(sec('workplace-evidence','Illustrative public-sector application','From fragmented reporting to defensible programme oversight.','This is an illustrative workplace scenario, not a verified learner testimonial or a guaranteed outcome.',grid([
('Challenge','Milestones, dependencies, risks and supplier updates in different formats limit confidence in the programme view.'),('Workplace application','Establish common data definitions, a controlled reporting cycle, clear ownership and an integrated decision log.'),('Governance improvement','Link schedule, cost, risk and change to the approved baseline in board papers, with escalation and recommended action.'),('Organisational value','Aim for earlier warning, clearer accountabilities and a repeatable internal controls process.'),('Workplace evidence','Record applied activity, assignments, professional reflection and employer feedback. Protect confidential information and review impact with the employer.')])) )
parts.append(sec('employers','Apprenticeship funding','Use the right funding route for the right employee.','The College reviews the employer, learner, role, programme and prior learning before confirming funding. Fully funded is not automatic: current rules, available funds, eligibility and the funding-band maximum apply.',grid([
('Levy-funded employers','Eligible organisations may use available apprenticeship-service funds for approved training and assessment.'),('Transfers and co-investment','Depending on the applicable rules and circumstances, levy transfers or government co-investment may support apprenticeship costs.'),('Available places','Any supported places or funding arrangements are subject to availability, eligibility and written confirmation.'),('Employer responsibilities','Support agreed paid learning activity, relevant workplace application, evidence opportunities, supervision and progress reviews.')],2)+'<div className="flex flex-wrap gap-3">'+link('/apprenticeship-eligibility-checker','Check employer eligibility')+link('/book-a-session','Request a funding review')+'</div>'))
parts.append(sec('career-support','Career development','Plan your next professional step.','Discuss role progression, planning, cost, risk, reporting, public-sector governance and preparation for senior responsibility.',link('/contact','Discuss your career development')))
# Retain the six genuine source FAQs, with site branding, without repeated source-template blocks.
source=json.loads(Path('docs/public-sector-source-tree.json').read_text(encoding='utf-8'))
def walk(n):
 if isinstance(n,dict):
  yield n
  for c in n['children']:yield from walk(c)
def text(n):return n if isinstance(n,str) else ' '.join(text(c) for c in n['children'])
faq=next(n for n in walk(source) if n['tag']=='section' and n['attrs'].get('id')=='eligibility')
rows=[]
for n in [n for n in walk(faq) if n['tag']=='details'][:6]:
 head=next(c for c in n['children'] if isinstance(c,dict) and c['tag']=='summary');body=' '.join(text(c) for c in n['children'] if c is not head).replace('Kent Business College','College of Project Controls')
 rows.append('<details className="rounded-xl border border-background-200 bg-white"><summary className="cursor-pointer p-5 font-bold">'+q(text(head))+'</summary><p className="px-5 pb-5 leading-relaxed text-foreground-600">'+q(body)+'</p></details>')
parts.append(sec('eligibility','Employer questions','Questions before you enquire.','Programme suitability, funding and assessment requirements are confirmed before enrolment.','<div className="max-w-4xl space-y-3">'+''.join(rows)+'</div>'))
parts.append(sec('next-step','Develop accountable project capability','Build teams that can plan, control and explain delivery.','Speak with the College about employee roles, suitable apprenticeship routes, funding eligibility and the next available cohort.',link('/book-a-session','Book an employer capability review')))
nav=[{'label':t,'href':'#'+i} for i,t in [('challenge','Challenge'),('pathways','Programmes'),('capability','Capability'),('governance','Governance'),('careers','Careers'),('delivery','Delivery'),('employers','Funding'),('eligibility','FAQ')]]
code="import SiteLink from '@/components/base/SiteLink';\nimport Footer from '@/components/feature/Footer';\nimport PageSectionNav from '@/components/feature/PageSectionNav';\nconst links = "+json.dumps(nav)+';\nexport default function Page() { return <div className="min-h-screen bg-background-50"><main id="hero">'+hero+'<PageSectionNav pageLabel="Public Sector" links={links} />'+''.join(parts)+'</main><Footer /></div>; }\n';p.write_text(code,encoding='utf-8')
