import { useEffect, useState } from 'react';
import { cmsApi } from '../api/client';
import EventbriteSettings from './EventbriteSettings';
import EventCategories from './EventCategories';
import type { EventCategory } from '@/services/eventsApi';

interface ManagedEvent { id: number; title: string; slug: string; source: string; description: string; summary: string; image_url: string; image_alt: string; starts_at: string | null; ends_at: string | null; timezone: string; location: string; format: string; cta_href: string; cta_label: string; remote_status: string; sales_status: string; is_active: boolean; is_featured: boolean; order: number; classifications: number[]; highlights_url: string; source_url: string; sync_error: string; public_visible: boolean }
const localKeys = ['summary', 'image_alt', 'is_active', 'is_featured', 'order', 'classifications', 'highlights_url'] as const;

export default function EventsManager() {
  const [tab, setTab] = useState('events'); const [events, setEvents] = useState<ManagedEvent[]>([]); const [categories, setCategories] = useState<EventCategory[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); const [busy, setBusy] = useState(false);
  const reload = async () => { const [items, terms] = await Promise.all([cmsApi.get<ManagedEvent[]>('/events/'), cmsApi.get<EventCategory[]>('/event-categories/')]); setEvents(items); setCategories(terms); };
  useEffect(() => { reload().catch(e => setError(e.message)).finally(() => setLoading(false)); }, []);
  const create = async () => { setBusy(true); try { await cmsApi.post('/events/', { title: 'New event', is_active: false }); await reload(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not create event.'); } finally { setBusy(false); } };
  return <div><h1 className="text-2xl font-bold">Events</h1><p className="mt-2 text-sm text-foreground-600">Manage events, publication rules and your Eventbrite connection.</p><div className="my-6 flex flex-wrap gap-2" role="tablist" aria-label="Events management">{[['events', 'Events'], ['categories', 'Categories & visibility'], ['connection', 'Eventbrite connection'], ['history', 'Sync history']].map(([key, label]) => <button key={key} role="tab" aria-selected={tab === key} onClick={() => { setTab(key); if (key === 'events' || key === 'categories') reload().catch(e => setError(e.message)); }} className={`rounded-lg px-4 py-3 text-sm font-semibold ${tab === key ? 'bg-primary-800 text-white' : 'border bg-white text-primary-800'}`}>{label}</button>)}</div>
    {error && <p role="alert" className="mb-5 text-red-700">{error}</p>}
    {tab === 'connection' || tab === 'history' ? <EventbriteSettings key={tab} history={tab === 'history'} /> : loading ? <p role="status">Loading events…</p> : tab === 'categories' ? <EventCategories categories={categories} reload={reload} /> : <><div className="mb-5 flex flex-wrap gap-4"><input type="search" aria-label="Search managed events" placeholder="Search events" value={search} onChange={e => setSearch(e.target.value)} className="min-w-0 flex-1 rounded-lg border p-3" /><button disabled={busy} onClick={create} className="btn-primary px-5 py-3 disabled:opacity-40">Add manual event</button><button onClick={() => reload().catch(e => setError(e.message))} className="rounded-lg border bg-white px-5 py-3">Refresh</button></div><div className="space-y-4">{events.filter(e => e.title.toLowerCase().includes(search.toLowerCase())).map(event => <Editor key={`${event.id}-${JSON.stringify(event)}`} event={event} categories={categories} reload={reload} />)}{events.length === 0 && <p>No events yet. Connect Eventbrite to import your events, or add a manual event.</p>}</div></>}
  </div>;
}

function Editor({ event, categories, reload }: { event: ManagedEvent; categories: EventCategory[]; reload: () => Promise<void> }) {
  const [form, setForm] = useState(event); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const imported = event.source === 'eventbrite';
  const set = <K extends keyof ManagedEvent>(key: K, value: ManagedEvent[K]) => setForm(prev => ({ ...prev, [key]: value }));
  const act = async (work: () => Promise<unknown>, message: string) => { setBusy(true); setError(''); try { await work(); setMessage(message); await reload(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save event.'); } finally { setBusy(false); } };
  const save = () => act(() => cmsApi.patch(`/events/${event.id}/`, imported ? Object.fromEntries(localKeys.map(key => [key, form[key]])) : { ...form, starts_at: form.starts_at || null, ends_at: form.ends_at || null }), 'Saved.');
  const text = (key: 'title' | 'image_url' | 'image_alt' | 'timezone' | 'location' | 'cta_href' | 'cta_label' | 'highlights_url', label: string, disabled = false) => <label className="text-sm font-semibold">{label}<input value={form[key]} disabled={disabled} onChange={e => set(key, e.target.value)} className="mt-2 w-full rounded-lg border px-3 py-2 text-sm font-normal disabled:bg-background-100" /></label>;
  return <details className="rounded-xl border bg-white p-5"><summary className="cursor-pointer font-semibold">{event.title}<span className={`ml-3 inline-block rounded px-2 py-1 text-xs ${event.public_visible ? 'bg-green-50 text-green-800' : 'bg-background-100 text-foreground-600'}`}>{event.public_visible ? 'Visible' : 'Hidden'}</span><span className="ml-3 text-xs font-normal">{imported ? 'Eventbrite' : 'Manual'} · {event.remote_status}</span></summary>
    <form onSubmit={e => { e.preventDefault(); save(); }} className="mt-5">{imported && <p className="mb-5 rounded-lg bg-background-100 p-4 text-sm">Edit the title, description, date, location and ticket details in Eventbrite. Local display settings below are preserved during sync.</p>}{error && <p role="alert" className="mb-4 text-sm text-red-700">{error}</p>}{message && <p role="status" className="mb-4 text-sm text-green-700">{message}</p>}{event.sync_error && <p className="mb-4 text-sm text-amber-800">{event.sync_error}</p>}
      <div className="grid gap-4 md:grid-cols-2">{text('title', 'Title', imported)}{text('image_url', 'Image URL', imported)}{text('image_alt', 'Image alternative text')}{text('timezone', 'Time zone', imported)}{(['starts_at', 'ends_at'] as const).map(key => <label key={key} className="text-sm font-semibold">{key === 'starts_at' ? 'Starts (ISO date with UTC offset)' : 'Ends (ISO date with UTC offset)'}<input value={form[key] || ''} disabled={imported} placeholder="2026-10-01T14:00:00+01:00" onChange={e => set(key, e.target.value || null)} className="mt-2 w-full rounded-lg border px-3 py-2 text-sm font-normal disabled:bg-background-100" /></label>)}{text('location', 'Location', imported)}<label className="text-sm font-semibold">Format<select value={form.format} disabled={imported} onChange={e => set('format', e.target.value)} className="mt-2 w-full rounded-lg border bg-white px-3 py-2"><option value="online">Online</option><option value="in_person">In person</option></select></label>
        <label className="text-sm font-semibold md:col-span-2">Description<textarea rows={5} value={form.description} disabled={imported} onChange={e => set('description', e.target.value)} className="mt-2 w-full rounded-lg border p-3 text-sm font-normal disabled:bg-background-100" /></label><label className="text-sm font-semibold md:col-span-2">Local summary<textarea rows={3} maxLength={600} value={form.summary} onChange={e => set('summary', e.target.value)} className="mt-2 w-full rounded-lg border p-3 text-sm font-normal" /></label>{text('cta_href', 'Registration link', imported)}{text('cta_label', 'Registration button label', imported)}{text('highlights_url', 'Highlights URL (shown after event ends)')}
        <label className="text-sm font-semibold">Display order<input type="number" min="0" value={form.order} onChange={e => set('order', Number(e.target.value))} className="mt-2 w-full rounded-lg border px-3 py-2" /></label>
        {!imported && <><label className="text-sm font-semibold">Event status<select value={form.remote_status} onChange={e => set('remote_status', e.target.value)} className="mt-2 w-full rounded-lg border bg-white p-2"><option value="live">Live</option><option value="draft">Draft</option><option value="cancelled">Cancelled</option></select></label><label className="text-sm font-semibold">Registration status<select value={form.sales_status} onChange={e => set('sales_status', e.target.value)} className="mt-2 w-full rounded-lg border bg-white p-2">{['unknown', 'available', 'sold_out', 'unavailable'].map(v => <option key={v} value={v}>{v.replaceAll('_', ' ')}</option>)}</select></label></>}
        <fieldset className="md:col-span-2"><legend className="text-sm font-semibold">Topics & programmes</legend><div className="mt-3 flex flex-wrap gap-4">{categories.filter(c => c.kind !== 'eventbrite').map(c => <label key={c.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.classifications.includes(c.id)} onChange={e => set('classifications', e.target.checked ? [...form.classifications, c.id] : form.classifications.filter(id => id !== c.id))} />{c.name}{!c.is_visible && ' (hidden)'}</label>)}</div></fieldset>
        <div className="flex flex-wrap gap-5 md:col-span-2"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_active} onChange={e => set('is_active', e.target.checked)} />Allow on public site</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_featured} onChange={e => set('is_featured', e.target.checked)} />Featured</label></div>
      </div><div className="mt-6 flex flex-wrap items-center gap-4"><button disabled={busy} className="btn-primary px-5 py-3 disabled:opacity-40">Save event</button>{event.public_visible && <a href={`/events/${event.slug}`} target="_blank" rel="noreferrer" className="text-sm underline">View event</a>}{imported ? <button type="button" disabled={busy} onClick={() => act(() => cmsApi.post(`/events/${event.id}/sync/`, {}), 'Sync queued.')} className="text-sm underline">Sync this event</button> : <button type="button" disabled={busy} onClick={() => { if (window.confirm('Delete this manual event?')) act(() => cmsApi.del(`/events/${event.id}/`), 'Deleted.'); }} className="text-sm text-red-700 underline">Delete</button>}</div>
    </form>
  </details>;
}
